task_traking/task_traking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_traking/tasks/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/complete/", TaskCompleteView.as_view(), name="task-complete"),
    path("comment/edit/<int:pk>/", CommentUpdateView.as_view(), name="edit_comment"),
    path("comment/delete/<int:pk>/", CommentDeleteView.as_view(), name="delete_comment"),
    path("comment/like/<int:pk>/", CommentLikeToggle.as_view(),
         name="comment-like-toggle"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

app_name = "tasks"

task_traking/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Система управління завданнями</title>
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">-->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link href="{% static 'css/site.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'tasks:task-list' %}">Головна</a>
        {% if user.is_authenticated %}
            <form action="{% url 'tasks:logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">
                    Вихід
                </button>
            </form>
        {% else %}
            <a class="navbar-brand" href="{% url 'tasks:login' %}">Вхід</a>
            <a class="navbar-brand" href="{% url 'tasks:register' %}">Реєстрація</a>
        {% endif %}
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>