task_traking/task_traking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_traking/tasks/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/complete/", TaskCompleteView.as_view(), name="task-complete"),
    path("comment/edit/<int:pk>/", CommentUpdateView.as_view(), name="edit_comment"),
    path("comment/delete/<int:pk>/", CommentDeleteView.as_view(), name="delete_comment"),
    path("comment/like/<int:pk>/", CommentLikeToggle.as_view(),
         name="comment-like-toggle"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

app_name = "tasks"

task_traking/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Task(models.Model):

    STATUS_CHOICES = [
        ("todo", "To Do"),
        ("in_progress", "In Progress"),
        ("done", "Done"),
    ]

    PRIORITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
    ]

    title = models.CharField(max_length=256)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="todo")
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default="medium")
    due_date = models.DateField(null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tasks:task-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    media = models.FileField(upload_to="comments_media/", blank=True, null=True)

    def get_absolute_url(self):
        return self.task.get_absolute_url()


class Like(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_comments')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('comment', 'user')  # Забезпечує унікальність лайків

task_traking/tasks/forms.py
from django import forms
from .models import Task, Comment


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "status", "priority", "due_date"]

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({"class": "form-control"})

        self.fields["due_date"].widget.attrs["class"] += " my-custom=datepicker"


class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ("", "Всі"),
        ("todo", "To Do"),
        ("in_progress", "In Progress"),
        ("done", "Done"),
    ]
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False, label="Статус")

    def __init__(self, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields["status"].widget.attrs.update({"class": "form-control"})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'media']
        widgets = {
            "media": forms.FileInput()
        }

task_traking/tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from tasks import models
from django.views.generic import ListView, DetailView, CreateView, View, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import TaskForm, TaskFilterForm, CommentForm
from django.http import HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .mixins import UserIsOwnerMixin


class TaskListView(ListView):
    model = models.Task
    context_object_name = "tasks"
    template_name = "tasks/task_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        status = self.request.GET.get("status", "")
        if status:
            queryset = queryset.filter(status=status)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TaskFilterForm(self.request.GET)
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = models.Task
    context_object_name = "task"
    template_name = 'tasks/task_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()  # Додаємо порожню форму коментаря в контекст
        return context

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST, request.FILES)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.task = self.get_object()
            comment.save()
            return redirect('tasks:task-detail', pk=comment.task.pk)
        else:
            # Тут можна обробити випадок з невалідною формою
            pass


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = models.Task
    template_name = "tasks/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TaskCompleteView(LoginRequiredMixin, UserIsOwnerMixin, View):
    def post(self, request, *args, **kwargs):
        task = self.get_object()
        task.status = "done"
        task.save()
        return HttpResponseRedirect(reverse_lazy("tasks:task-list"))

    def get_object(self):
        task_id = self.kwargs.get("pk")
        return get_object_or_404(models.Task, pk=task_id)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Task
    form_class = TaskForm
    template_name = "tasks/task_update_form.html"
    success_url = reverse_lazy("tasks:task-list")


class TaskDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = models.Task
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_delete_confirmation.html"


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Comment
    fields = ['content']
    template_name = 'tasks/edit_comment.html'

    def form_valid(self, form):
        comment = self.get_object()
        if comment.author != self.request.user:
            raise PermissionDenied("Ви не можете редагувати цей коментар.")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('tasks:task_detail', kwargs={'pk': self.object.task.pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Comment
    template_name = 'tasks/delete_comment.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user)

    def get_success_url(self):
        return reverse_lazy('tasks:task_detail', kwargs={'pk': self.object.task.pk})


class CommentLikeToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(models.Comment, pk=self.kwargs.get('pk'))
        like_qs = models.Like.objects.filter(comment=comment, user=request.user)
        if like_qs.exists():
            like_qs.delete()
        else:
            models.Like.objects.create(comment=comment, user=request.user)
        return HttpResponseRedirect(comment.get_absolute_url())


class CustomLoginView(LoginView):
    template_name = "tasks/login.html"
    redirect_authenticated_user = True


class CustomLogoutView(LogoutView):
    next_page = "tasks:login"


class RegisterView(CreateView):
    template_name = "tasks/register.html"
    form_class = UserCreationForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse_lazy("tasks:login"))

task_traking/templates/tasks/delete_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Ви впевнені, що хочете видалити цей коментар?</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Видалити</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Відміна</a>
    </form>
</div>
{% endblock %}

task_traking/templates/tasks/edit_comment.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Редагувати коментар</h2>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити</button>
    </form>
</div>
{% endblock %}

task_traking/templates/tasks/login.html
{% extends 'base.html' %}

{% block content %}
<div class="login">
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
    </div>
{% endblock %}

task_traking/templates/tasks/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>
{% endblock %}

task_traking/templates/tasks/task_delete_confirmation.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Видалення завдання</h2>
    <p>Ви впевнені, що хочете видалити завдання "{{ object.title }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Так, видалити</button>
        <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">Ні, повернутися до списку завдань</a>
    </form>
</div>
{% endblock %}

task_traking/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block content %}
{% load custom_tags %}
<div class="container mt-3">
    <h2>{{ task.title }}</h2>
    <p>{{ task.description }}</p>
    <p>Статус: <span class="badge badge-primary">{{ task.status }}</span></p>
    <p>Пріоритет: <span class="badge badge-secondary">{{ task.priority }}</span></p>
    <a href="{% url 'tasks:task-update' task.id %}" class="btn btn-warning">Редагувати</a>
    <a href="{% url 'tasks:task-delete' task.id %}" class="btn btn-danger">Видалити</a>

    <!-- Коментарі -->
    <div class="comments mt-4">
        <h3>Коментарі</h3>
        {% for comment in task.comments.all %}
            <div class="comment mb-2">
                <p>{{ comment.content }}</p>
                {% if comment.media %}
                    <div class="comment-media">
                        {% if comment.media.url|endswith:".jpg" or comment.media.url|endswith:".png" or comment.media.url|endswith:".jpeg" %}
                            <img src="{{ comment.media.url }}" alt="Зображення коментаря" style="max-width: 1000px;">
                        {% elif comment.media.url|endswith:".mp4" %}
                            <video width="320" height="240" controls>
                                <source src="{{ comment.media.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        {% else %}
                            <a href="{{ comment.media.url }}">Завантажити файл</a>
                        {% endif %}
                    </div>
                {% endif %}
                <small>Автор: {{ comment.author.username }}</small>
                <form action="{% url 'tasks:comment-like-toggle' comment.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm {% if request.user in comment.likes.all %}btn-success{% else %}btn-outline-success{% endif %}">
                        Лайк {{ comment.likes.count }}
                    </button>
                </form>
            </div>
        {% empty %}
            <p>Коментарі відсутні.</p>
        {% endfor %}
    </div>

    <!-- Форма додавання коментаря -->
    <div class="add-comment mt-4">
        <h4>Додати коментар</h4>
        <form action="{% url 'tasks:task-detail' task.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Відправити</button>
        </form>
    </div>
</div>
{% endblock %}

task_traking/templates/tasks/task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>{{ view.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Зберегти</button>
    </form>
</div>
{% endblock %}

task_traking/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Список завдань</h2>
    <a href="{% url 'tasks:task-create'%}" class="btn btn-primary mb-3">Додати завдання</a>

    <br>

    <form method="get" class="form-inline mb-3">
        {{ form.status.label_tag }}
        {{ form.status }}
        <button type="submit" class="btn btn-primary ml-2">Фільтрувати</button>
    </form>

    <ul class="list-group">
        {% for task in tasks %}

        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <a href="{% url 'tasks:task-detail' task.pk %}">{{ task.title }}</a>
                <span class="badge badge-primary">{{ task.status }}</span>
                <span class="badge badge-secondary">{{ task.priority }}</span>
            </div>
            <form action="{% url 'tasks:task-complete' task.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning btn-sm">Помітити як виконано</button>
            </form>
        </li>
        {% empty %}
        <li class="list-group-item">Завдань не знайдено.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

task_traking/templates/tasks/task_update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Оновлення завдання</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Оновити завдання</button>
        <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">Назад до списку завдань</a>
    </form>
</div>
{% endblock %}